- hosts: master:slave
  user: vagrant
  tasks:
  - name: Install MySQL Server
    apt: name=mysql-server state=latest update_cache=yes

  - name: Install pip3
    apt: name=python3-pip state=latest update_cache=yes

  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
      name: pymysql
      state: present

#  - name: Write root login credentials
#    copy:
#      dest: /root/.my.cnf
#      owner: root
#      group: root
#      mode: 0600
#      content: |
#          [client]
#          user=root
#          password=abc123

#  - name: Specify MySQL root password before installing
#    debconf: name='mysql-server' question='mysql-server/root_password' value='"abc123"' vtype='password'
#    become: true

#  - name: Confirm MySQL root password before installing
#    debconf: name='mysql-server' question='mysql-server/root_password_again' value='"abc123"' vtype='password'
#    become: true

  - name: Set root user password
    mysql_user:
      name: root
      host: "%"
      password: abc123
      # Login without credentials
      check_implicit_admin: yes
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

#  - name: Test root connect
#    mysql_user:
#      name: root
#      password: abc123
#      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Create replication account
    mysql_user: 
      name: repl 
      host: "%" 
      password: s3cr3tPaSSwordR 
      priv: "*.*:REPLICATION CLIENT" 
      state: present 
      login_unix_socket: /var/run/mysqld/mysqld.sock 

  - name: Create readwrite user
    mysql_user: 
      name: rwuser 
      host: "%" 
      password: s3cr3tPaSSwordR 
      priv: "*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP" 
      state: present 
      login_unix_socket: /var/run/mysqld/mysqld.sock 

#  - name: Check /my.cnf mysqld.cnf
#    debug: var=item
#    with_file:
#      - "/etc/mysql/my.cnf"
#      - "/etc/mysql/mysql.conf.d/mysqld.cnf"

  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^bind-address" line="bind-address=0.0.0.0"

- hosts: master
  user: vagrant
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^#server-id" line="server-id=1"
  - name: Restart mysql service
    service: name=mysql state=restarted
  - name: Reset master binlog
    command: /usr/bin/mysql -u root -e "RESET MASTER"

- hosts: slave
  user: vagrant
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^#server-id" line="server-id=2"

  - name: Restart mysql service
    service: name=mysql state=restarted
  
  #- name: Set root user password
  #  mysql_user:
  #    name: root
  #    host: "%"
  #    password: abc123
  #    # Login without credentials
  #    check_implicit_admin: yes
  #    state: present
  #    login_unix_socket: /var/run/mysqld/mysqld.sock

#  - name: Setup replication
#    command: /usr/bin/mysql -uroot -e "CHANGE MASTER TO master_host='192.168.10.2', master_user='repl', master_password='s3cr3tPaSSwordR', master_use_gtid=current_pos"

#  - name: Setup replication
#    mysql_replication:
#      mode: changemaster
#      master_user: repl
#      master_password: s3cr3tPaSSwordR
#      master_host: 192.168.10.2
##      master_log_file: mysql-bin.000009
##      master_log_pos: current_pos
#      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Restart mysql service
    service: name=mysql state=restarted

  - name: Get master binlog file name and binlog position
    mysql_replication:
      mode: getmaster
      master_user: repl
      master_password: s3cr3tPaSSwordR
      master_host: 192.168.10.2
##      master_log_file: mysql-bin.000009
##      master_log_pos: current_pos
      login_unix_socket: /var/run/mysqld/mysqld.sock

#  - name: Check slave status
#    mysql_replication:
#      mode: getslave
