- hosts: master:slave
  user: vagrant
  tasks:
  - name: Install MySQL Server
    apt: name=mysql-server state=latest update_cache=yes

  - name: Install pip3
    apt: name=python3-pip state=latest update_cache=yes

  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
      name: pymysql
      state: present

#  - name: Write root login credentials
#    copy:
#      dest: /root/.my.cnf
#      owner: root
#      group: root
#      mode: 0600
#      content: |
#          [client]
#          user=root
#          password=abc123

#  - name: Specify MySQL root password before installing
#    debconf: name='mysql-server' question='mysql-server/root_password' value='"abc123"' vtype='password'
#    become: true

#  - name: Confirm MySQL root password before installing
#    debconf: name='mysql-server' question='mysql-server/root_password_again' value='"abc123"' vtype='password'
#    become: true

  - name: Set root user password
    mysql_user:
      name: root
      host: "%"
      password: abc123
      # Login without credentials
      check_implicit_admin: yes
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

#  - name: Test root connect
#    mysql_user:
#      name: root
#      password: abc123
#      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Create replication account
    mysql_user: 
      name: repl 
      host: "%" 
      password: s3cr3tPaSSwordR 
      priv: "*.*:REPLICATION CLIENT" 
      state: present 
      login_unix_socket: /var/run/mysqld/mysqld.sock 

  - name: Create readwrite user
    mysql_user: 
      name: rwuser 
      host: "%" 
      password: s3cr3tPaSSwordR 
      priv: "*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP" 
      state: present 
      login_unix_socket: /var/run/mysqld/mysqld.sock 

  - name: Check /etc/mysql/my.cnf
    debug: var=item
    with_file:
      - "/etc/mysql/my.cnf"
      - "~/my.cnf"

  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address=0.0.0.0"

- hosts: master
  user: vagrant
  tasks:
#  - name: Modify configuration file to setup server ID
#    lineinfile: dest=/etc/mysql/my.cnf regexp="^#server-id" line="server-id=1"
  - name: Restart mysql service
    service: name=mysql state=restarted
#  - name: Reset master binlog
#    command: /usr/bin/mysql -u root -e "RESET MASTER"

- hosts: slave
  user: vagrant
  tasks:
#  - name: Modify configuration file to setup server ID
#    lineinfile: dest=/etc/mysql/my.cnf regexp="^#server-id" line="server-id=2"
#  - name: Setup replication
#    command: /usr/bin/mysql -uroot -e "CHANGE MASTER TO master_host='192.168.10.2', master_user='repl', master_password='s3cr3tPaSSwordR', master_use_gtid=current_pos"
  - name: Restart mysql service
    service: name=mysql state=restarted
