- hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt cache
      action: apt update_cache=yes
      sudo: yes

    - name: Upgrade
      action: apt upgrade=yes
      sudo: yes

    - name: Install required packages
      action: apt name={{ item }}
      sudo: yes
      with_items:
        - mc
        - rsync
        - htop
        - screen
        - aptitude
